# Generated by Django 5.1.3 on 2024-12-31 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='name',
            new_name='title',
        ),
    ]
