# Generated by Django 5.1.3 on 2025-01-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskCategory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcategory',
            name='taskModel',
        ),
    ]
